# Generated by Django 5.2.8 on 2025-12-11 04:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminapp', '0001_initial'),
        ('doctorapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDetail',
            fields=[
                ('PAT_ID', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Patient ID')),
                ('Patient_Name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Patient name can only contain letters, spaces, dots and hyphens', regex='^[A-Za-z\\s\\.\\-]+$')])),
                ('DOB', models.DateField()),
                ('Address', models.TextField()),
                ('Phone_Number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits (no symbols or spaces)', regex='^\\d{10}$')])),
                ('Email', models.EmailField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid email address with proper domain', regex='^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$')])),
                ('Gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True)),
                ('Blood_Group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=5, null=True)),
                ('Emergency_Contact', models.CharField(blank=True, max_length=10, null=True)),
                ('Occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'PATIENT_DETAILS',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BillDetail',
            fields=[
                ('BILL_ID', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Bill ID')),
                ('Consultation_Cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Medicine_Cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('LabTest_Cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Additional_Charges', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Total_Amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Pay_Status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Partial', 'Partial'), ('Insurance Pending', 'Insurance Pending'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('Payment_Mode', models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Card', 'Card'), ('Online', 'Online'), ('Insurance', 'Insurance'), ('Mixed', 'Mixed')], max_length=20, null=True)),
                ('Payment_Date', models.DateTimeField(blank=True, null=True)),
                ('Transaction_ID', models.CharField(blank=True, max_length=100, null=True)),
                ('Notes', models.TextField(blank=True, null=True)),
                ('Created_Date', models.DateTimeField(auto_now_add=True)),
                ('Updated_Date', models.DateTimeField(auto_now=True)),
                ('CONSULT_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctorapp.consultationdetail')),
            ],
            options={
                'db_table': 'BILL_DETAILS',
                'ordering': ['-Created_Date'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentDetail',
            fields=[
                ('APPOINTMENT_ID', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Appointment ID')),
                ('TOKEN_NO', models.CharField(max_length=20, verbose_name='Token Number')),
                ('Status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=20)),
                ('Date', models.DateField()),
                ('Time', models.TimeField(default='09:00:00')),
                ('Priority', models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent'), ('critical', 'Critical')], default='normal', max_length=20)),
                ('Reason', models.TextField(blank=True, null=True)),
                ('Notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_by', models.CharField(blank=True, max_length=50, null=True)),
                ('DOC_ID', models.ForeignKey(limit_choices_to={'Role': 'Doctor'}, on_delete=django.db.models.deletion.CASCADE, to='adminapp.staffdetail')),
                ('PAT_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='receptionistapp.patientdetail')),
            ],
            options={
                'db_table': 'APPOINTMENT_DETAILS',
                'ordering': ['-Priority', 'Date', 'Time'],
            },
        ),
        migrations.CreateModel(
            name='PatientMedicalInfo',
            fields=[
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='medical_info', serialize=False, to='receptionistapp.patientdetail', verbose_name='Patient')),
                ('past_medical_history', models.TextField(blank=True, help_text='Previous illnesses, surgeries, hospitalizations', null=True, verbose_name='Past Medical History')),
                ('allergies', models.TextField(blank=True, help_text='Drug allergies, food allergies, environmental allergies', null=True, verbose_name='Allergies')),
                ('chronic_conditions', models.TextField(blank=True, help_text='Diabetes, Hypertension, Asthma, etc.', null=True, verbose_name='Chronic Conditions')),
                ('current_medications', models.TextField(blank=True, help_text='Regular medications being taken', null=True, verbose_name='Current Medications')),
                ('family_history', models.TextField(blank=True, help_text='Family medical history', null=True, verbose_name='Family History')),
                ('social_history', models.TextField(blank=True, help_text='Smoking, alcohol, occupation, lifestyle', null=True, verbose_name='Social History')),
                ('surgical_history', models.TextField(blank=True, help_text='Previous surgeries with dates', null=True, verbose_name='Surgical History')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Height (cm)')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Weight (kg)')),
                ('blood_pressure', models.CharField(blank=True, max_length=20, null=True, verbose_name='Blood Pressure')),
                ('pulse', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(200)], verbose_name='Pulse (BPM)')),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(35.0), django.core.validators.MaxValueValidator(42.0)], verbose_name='Temperature (°C)')),
                ('respiratory_rate', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(8), django.core.validators.MaxValueValidator(60)], verbose_name='Respiratory Rate')),
                ('oxygen_saturation', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(70), django.core.validators.MaxValueValidator(100)], verbose_name='O2 Saturation (%)')),
                ('additional_notes', models.TextField(blank=True, null=True, verbose_name='Additional Notes')),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_by', models.ForeignKey(blank=True, limit_choices_to={'Role': 'Doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapp.staffdetail', verbose_name='Last Updated By')),
            ],
            options={
                'verbose_name': 'Patient Medical Information',
                'verbose_name_plural': 'Patients Medical Information',
                'db_table': 'PATIENT_MEDICAL_INFO',
            },
        ),
    ]
