# Generated by Django 5.2.8 on 2025-12-04 17:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminapp', '0001_initial'),
        ('doctorapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDetail',
            fields=[
                ('PAT_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Patient_Name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Patient name can only contain letters, spaces, dots and hyphens', regex='^[A-Za-z\\s\\.\\-]+$')])),
                ('DOB', models.DateField()),
                ('Address', models.CharField(max_length=255)),
                ('Phone_Number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits (no symbols or spaces)', regex='^\\d{10}$')])),
                ('Email', models.EmailField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid email address with proper domain', regex='^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$')])),
            ],
            options={
                'db_table': 'PATIENT_DETAILS',
            },
        ),
        migrations.CreateModel(
            name='ReceptionistLog',
            fields=[
                ('LOG_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Action', models.CharField(max_length=255)),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
                ('Details', models.TextField()),
            ],
            options={
                'db_table': 'RECEPTIONIST_LOGS',
            },
        ),
        migrations.CreateModel(
            name='BillDetail',
            fields=[
                ('BILL_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Consultation_Cost', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('Medicine_Cost', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('LabTest_Cost', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('Total_Amount', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('Pay_Status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Partial', 'Partial'), ('Insurance Pending', 'Insurance Pending'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('Payment_Mode', models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Card', 'Card'), ('Online', 'Online'), ('Insurance', 'Insurance'), ('Mixed', 'Mixed')], max_length=20, null=True)),
                ('Created_Date', models.DateTimeField(auto_now_add=True)),
                ('CONSULT_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctorapp.consultationdetail')),
            ],
            options={
                'db_table': 'BILL_DETAILS',
            },
        ),
        migrations.CreateModel(
            name='AppointmentDetail',
            fields=[
                ('TOKEN_NO', models.AutoField(primary_key=True, serialize=False)),
                ('Status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=20)),
                ('Date', models.DateField()),
                ('Priority', models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent'), ('critical', 'Critical')], default='normal', max_length=20)),
                ('DOC_ID', models.ForeignKey(limit_choices_to={'Role': 'Doctor'}, on_delete=django.db.models.deletion.CASCADE, to='adminapp.staffdetail')),
                ('PAT_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receptionistapp.patientdetail')),
            ],
            options={
                'db_table': 'APPOINTMENT_DETAILS',
                'ordering': ['-Priority', 'Date'],
            },
        ),
    ]
