# Generated by Django 5.2.8 on 2025-12-07 07:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminapp', '0001_initial'),
        ('doctorapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDetail',
            fields=[
                ('PAT_ID', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Patient ID')),
                ('Patient_Name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Patient name can only contain letters, spaces, dots and hyphens', regex='^[A-Za-z\\s\\.\\-]+$')])),
                ('DOB', models.DateField()),
                ('Address', models.TextField()),
                ('Phone_Number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits (no symbols or spaces)', regex='^\\d{10}$')])),
                ('Email', models.EmailField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid email address with proper domain', regex='^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$')])),
                ('Gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True)),
                ('Blood_Group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=5, null=True)),
                ('Emergency_Contact', models.CharField(blank=True, max_length=10, null=True)),
                ('Occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'PATIENT_DETAILS',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BillDetail',
            fields=[
                ('BILL_ID', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Bill ID')),
                ('Consultation_Cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Medicine_Cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('LabTest_Cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Additional_Charges', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Total_Amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Pay_Status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Partial', 'Partial'), ('Insurance Pending', 'Insurance Pending'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('Payment_Mode', models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Card', 'Card'), ('Online', 'Online'), ('Insurance', 'Insurance'), ('Mixed', 'Mixed')], max_length=20, null=True)),
                ('Payment_Date', models.DateTimeField(blank=True, null=True)),
                ('Transaction_ID', models.CharField(blank=True, max_length=100, null=True)),
                ('Notes', models.TextField(blank=True, null=True)),
                ('Created_Date', models.DateTimeField(auto_now_add=True)),
                ('Updated_Date', models.DateTimeField(auto_now=True)),
                ('CONSULT_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctorapp.consultationdetail')),
            ],
            options={
                'db_table': 'BILL_DETAILS',
                'ordering': ['-Created_Date'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentDetail',
            fields=[
                ('APPOINTMENT_ID', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Appointment ID')),
                ('TOKEN_NO', models.CharField(max_length=20, verbose_name='Token Number')),
                ('Status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=20)),
                ('Date', models.DateField()),
                ('Time', models.TimeField(default='09:00:00')),
                ('Priority', models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent'), ('critical', 'Critical')], default='normal', max_length=20)),
                ('Reason', models.TextField(blank=True, null=True)),
                ('Notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_by', models.CharField(blank=True, max_length=50, null=True)),
                ('DOC_ID', models.ForeignKey(limit_choices_to={'Role': 'Doctor'}, on_delete=django.db.models.deletion.CASCADE, to='adminapp.staffdetail')),
                ('PAT_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='receptionistapp.patientdetail')),
            ],
            options={
                'db_table': 'APPOINTMENT_DETAILS',
                'ordering': ['-Priority', 'Date', 'Time'],
            },
        ),
    ]
