# Generated by Django 5.2.8 on 2025-12-11 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0004_consultationdetail_created_date_and_more'),
        ('receptionistapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billdetail',
            name='auto_generated',
            field=models.BooleanField(default=False, verbose_name='Auto-generated'),
        ),
        migrations.AlterField(
            model_name='billdetail',
            name='CONSULT_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='doctorapp.consultationdetail'),
        ),
    ]
