# Generated by Django 5.2.8 on 2025-12-12 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptionistapp', '0002_billdetail_auto_generated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentdetail',
            name='APPOINTMENT_ID',
            field=models.CharField(default='temp', max_length=20, primary_key=True, serialize=False, verbose_name='Appointment ID'),
        ),
    ]
