# Generated by Django 5.2.8 on 2025-11-19 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTestRequestDetails',
            fields=[
                ('LAB_REQUEST_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Requested_Date', models.DateTimeField(auto_now_add=True)),
                ('Status', models.CharField(choices=[('Requested', 'Requested'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Requested', max_length=20)),
                ('Notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'DOCTOR_LAB_REQUESTS',
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('PRESCRIPTION_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Dosage', models.CharField(max_length=100)),
                ('Frequency', models.CharField(choices=[('1-0-1', '1-0-1 (Morning-Night)'), ('0-1-1', '0-1-1 (Afternoon-Night)'), ('1-0-0', '1-0-0 (Morning only)'), ('0-1-0', '0-1-0 (Afternoon only)'), ('0-0-1', '0-0-1 (Night only)'), ('1-1-0', '1-1-0 (Morning-Afternoon)'), ('1-1-1', '1-1-1 (Morning-Afternoon-Night)')], default='1-0-1', max_length=10)),
                ('Duration', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'PRESCRIPTION',
            },
        ),
        migrations.CreateModel(
            name='ConsultationDetails',
            fields=[
                ('CONSULT_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Symptoms', models.TextField()),
                ('Diagnosis', models.TextField()),
                ('Description', models.TextField(blank=True)),
                ('Consultation_Time', models.DateTimeField(auto_now_add=True)),
                ('DOC_ID', models.ForeignKey(limit_choices_to={'Role': 'Doctor'}, on_delete=django.db.models.deletion.CASCADE, to='adminapp.staffdetails')),
            ],
            options={
                'db_table': 'CONSULTATION_DETAILS',
            },
        ),
    ]
