# Generated by Django 5.2.8 on 2025-12-04 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTestRequestDetail',
            fields=[
                ('LAB_REQUEST_ID', models.AutoField(primary_key=True, serialize=False, verbose_name='Lab Request ID')),
                ('Priority', models.CharField(choices=[('routine', 'Routine'), ('priority', 'Priority'), ('stat', 'Stat (Immediate)')], default='routine', max_length=20, verbose_name='Priority')),
                ('Requested_Date', models.DateTimeField(auto_now_add=True, verbose_name='Requested Date')),
                ('Status', models.CharField(choices=[('Requested', 'Requested'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Requested', max_length=20, verbose_name='Status')),
                ('Notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Lab Test Request',
                'verbose_name_plural': 'Lab Test Requests',
                'db_table': 'DOCTOR_LAB_REQUESTS',
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('PRESCRIPTION_ID', models.AutoField(primary_key=True, serialize=False, verbose_name='Prescription ID')),
                ('Dosage', models.CharField(max_length=100, verbose_name='Dosage')),
                ('Frequency', models.CharField(choices=[('1-0-1', '1-0-1 (Morning-Night)'), ('0-1-1', '0-1-1 (Afternoon-Night)'), ('1-0-0', '1-0-0 (Morning only)'), ('0-1-0', '0-1-0 (Afternoon only)'), ('0-0-1', '0-0-1 (Night only)'), ('1-1-0', '1-1-0 (Morning-Afternoon)'), ('1-1-1', '1-1-1 (Morning-Afternoon-Night)')], default='1-0-1', max_length=10, verbose_name='Frequency')),
                ('Duration', models.CharField(max_length=50, verbose_name='Duration')),
            ],
            options={
                'verbose_name': 'Prescription',
                'verbose_name_plural': 'Prescriptions',
                'db_table': 'PRESCRIPTIONS',
            },
        ),
        migrations.CreateModel(
            name='ConsultationDetail',
            fields=[
                ('CONSULT_ID', models.AutoField(primary_key=True, serialize=False, verbose_name='Consultation ID')),
                ('Symptoms', models.TextField(verbose_name='Symptoms')),
                ('Diagnosis', models.TextField(verbose_name='Diagnosis')),
                ('Description', models.TextField(blank=True, verbose_name='Description')),
                ('Consultation_Status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='not_started', max_length=20, verbose_name='Consultation Status')),
                ('Consultation_Time', models.DateTimeField(auto_now_add=True, verbose_name='Consultation Time')),
                ('DOC_ID', models.ForeignKey(limit_choices_to={'Role': 'Doctor'}, on_delete=django.db.models.deletion.CASCADE, to='adminapp.staffdetail', verbose_name='Doctor')),
            ],
            options={
                'verbose_name': 'Consultation Detail',
                'verbose_name_plural': 'Consultation Details',
                'db_table': 'CONSULTATION_DETAILS',
            },
        ),
    ]
