# Generated by Django 5.2.8 on 2025-12-04 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminapp', '0001_initial'),
        ('doctorapp', '0001_initial'),
        ('labtechapp', '0001_initial'),
        ('pharmacistapp', '0001_initial'),
        ('receptionistapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationdetail',
            name='TOKEN_NO',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receptionistapp.appointmentdetail', verbose_name='Token Number'),
        ),
        migrations.AddField(
            model_name='labtestrequestdetail',
            name='Assigned_Technician',
            field=models.ForeignKey(blank=True, limit_choices_to={'Role': 'Lab Technician'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapp.staffdetail', verbose_name='Assigned Technician'),
        ),
        migrations.AddField(
            model_name='labtestrequestdetail',
            name='CONSULT_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_lab_requests', to='doctorapp.consultationdetail', verbose_name='Consultation'),
        ),
        migrations.AddField(
            model_name='labtestrequestdetail',
            name='LAB_TEST_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_test_requests', to='labtechapp.labtest', verbose_name='Lab Test'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='CONSULT_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctorapp.consultationdetail', verbose_name='Consultation'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='MED_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacistapp.medicinedetail', verbose_name='Medicine'),
        ),
    ]
