# Generated by Django 5.2.8 on 2025-11-19 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctorapp', '0001_initial'),
        ('labtechapp', '0001_initial'),
        ('pharmacistapp', '0001_initial'),
        ('receptionistapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationdetails',
            name='TOKEN_NO',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receptionistapp.appointmentdetails'),
        ),
        migrations.AddField(
            model_name='labtestrequestdetails',
            name='CONSULT_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_lab_requests', to='doctorapp.consultationdetails'),
        ),
        migrations.AddField(
            model_name='labtestrequestdetails',
            name='LAB_TEST_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_test_requests', to='labtechapp.labtests'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='CONSULT_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctorapp.consultationdetails'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='MED_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacistapp.medicinedetails'),
        ),
    ]
