# Generated by Django 5.2.8 on 2025-12-11 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0002_initial'),
    ]

    operations = [
    ]
