# Generated by Django 5.2.8 on 2025-12-11 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0003_fix_consultation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationdetail',
            name='Created_Date',
            field=models.DateTimeField(auto_now_add=True, default='2024-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consultationdetail',
            name='CONSULT_ID',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Consultation ID'),
        ),
    ]
