# Generated by Django 5.2.8 on 2025-11-19 11:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctorapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTests',
            fields=[
                ('LAB_TEST_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Lab_Test_Name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Lab test name can only contain letters, numbers, spaces, hyphens and parentheses', regex='^[A-Za-z0-9\\s\\-\\(\\)]+$')])),
                ('Lab_Test_Cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='Lab test cost cannot be negative'), django.core.validators.MinValueValidator(1, message='Lab test cost must be at least 1')])),
                ('Description', models.TextField(blank=True, validators=[django.core.validators.RegexValidator(message='Description can only contain letters, numbers, spaces and basic punctuation', regex='^[A-Za-z0-9\\s\\.,!?\\-\\(\\):;]+$')])),
            ],
            options={
                'db_table': 'LAB_TESTS',
            },
        ),
        migrations.CreateModel(
            name='LabTestResults',
            fields=[
                ('RESULT_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Findings', models.TextField(validators=[django.core.validators.RegexValidator(message='Findings can only contain letters, numbers, spaces and basic punctuation', regex='^[A-Za-z0-9\\s\\.,!?\\-\\(\\):;/]+$')])),
                ('Normal_Range', models.CharField(blank=True, max_length=100, validators=[django.core.validators.RegexValidator(message='Normal range can only contain letters, numbers, spaces, hyphens and dots', regex='^[A-Za-z0-9\\s\\-\\–\\.]+$')])),
                ('Remarks', models.TextField(blank=True, validators=[django.core.validators.RegexValidator(message='Remarks can only contain letters, numbers, spaces and basic punctuation', regex='^[A-Za-z0-9\\s\\.,!?\\-\\(\\):;]+$')])),
                ('Result_Date', models.DateTimeField(auto_now_add=True)),
                ('LAB_REQUEST', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='doctorapp.labtestrequestdetails')),
            ],
            options={
                'db_table': 'LAB_TEST_RESULTS',
            },
        ),
    ]
