# Generated by Django 5.2.8 on 2025-12-03 08:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctorapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('LAB_TEST_ID', models.AutoField(primary_key=True, serialize=False, verbose_name='Lab Test ID')),
                ('Lab_Test_Name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Lab test name can only contain letters, numbers, spaces, hyphens and parentheses', regex='^[A-Za-z0-9\\s\\-\\(\\)]+$')], verbose_name='Lab Test Name')),
                ('Lab_Test_Cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='Lab test cost cannot be negative'), django.core.validators.MinValueValidator(1, message='Lab test cost must be at least 1')], verbose_name='Lab Test Cost')),
                ('Description', models.TextField(blank=True, validators=[django.core.validators.RegexValidator(message='Description can only contain letters, numbers, spaces and basic punctuation', regex='^[A-Za-z0-9\\s\\.,!?\\-\\(\\):;]+$')], verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Lab Test',
                'verbose_name_plural': 'Lab Tests',
                'db_table': 'LAB_TESTS',
            },
        ),
        migrations.CreateModel(
            name='LabTestResult',
            fields=[
                ('RESULT_ID', models.AutoField(primary_key=True, serialize=False, verbose_name='Result ID')),
                ('Findings', models.TextField(validators=[django.core.validators.RegexValidator(message='Findings can only contain letters, numbers, spaces and basic punctuation', regex='^[A-Za-z0-9\\s\\.,!?\\-\\(\\):;/]+$')], verbose_name='Findings')),
                ('Normal_Range', models.CharField(blank=True, max_length=100, validators=[django.core.validators.RegexValidator(message='Normal range can only contain letters, numbers, spaces, hyphens and dots', regex='^[A-Za-z0-9\\s\\-\\–\\.]+$')], verbose_name='Normal Range')),
                ('Remarks', models.TextField(blank=True, validators=[django.core.validators.RegexValidator(message='Remarks can only contain letters, numbers, spaces and basic punctuation', regex='^[A-Za-z0-9\\s\\.,!?\\-\\(\\):;]+$')], verbose_name='Remarks')),
                ('Result_Date', models.DateTimeField(auto_now_add=True, verbose_name='Result Date')),
                ('LAB_REQUEST', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='doctorapp.labtestrequestdetail', verbose_name='Lab Request')),
            ],
            options={
                'verbose_name': 'Lab Test Result',
                'verbose_name_plural': 'Lab Test Results',
                'db_table': 'LAB_TEST_RESULTS',
            },
        ),
    ]
