# Generated by Django 5.2.8 on 2025-12-05 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginhistory',
            name='logout_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loginhistory',
            name='session_duration',
            field=models.IntegerField(blank=True, help_text='Session duration in seconds', null=True),
        ),
    ]
