// src/modules/admin/components/AddAccountModal.jsx - FIXED VERSION
import React, { useState, useEffect } from "react";
import { adminApi } from "../services/adminApi.js";

const AddAccountModal = ({ staff, show, onClose, onSuccess }) => {
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [success, setSuccess] = useState("");
  const [mode, setMode] = useState("create"); // 'create' or 'link'
  const [availableUsers, setAvailableUsers] = useState([]);
  const [selectedUserId, setSelectedUserId] = useState("");
  
  const [usernameOption, setUsernameOption] = useState("auto"); // "auto" or "custom"
  const [usernameAutoGenerated, setUsernameAutoGenerated] = useState("");
  
  const [formData, setFormData] = useState({
    username: "",
    email: staff?.Email || "",
    password: "",
    confirm_password: "",
  });

  useEffect(() => {
    if (show && staff) {
      // Reset all states when modal opens
      setError("");
      setSuccess("");
      setLoading(false);
      setUsernameOption("auto");
      setSelectedUserId("");
      
      // Pre-fill email from staff
      setFormData(prev => ({
        username: "",
        email: staff.Email,
        password: "",
        confirm_password: "",
      }));
      
      // Generate auto username
      const autoUsername = generateAutoUsername(staff);
      setUsernameAutoGenerated(autoUsername);
      
      // Set auto-generated username as default
      setFormData(prev => ({
        ...prev,
        username: autoUsername
      }));
      
      fetchAvailableUsers();
    }
  }, [show, staff]);

  const generateAutoUsername = (staff) => {
    // Generate username in format: firstname.lastname.staffid
    const nameParts = staff.Name.toLowerCase().split(' ');
    const firstName = nameParts[0];
    const lastName = nameParts.length > 1 ? nameParts[nameParts.length - 1] : "";
    let username = "";
    
    if (lastName) {
      username = `${firstName}.${lastName}.${staff.STAFF_ID}`;
    } else {
      username = `${firstName}.${staff.STAFF_ID}`;
    }
    
    // Clean the username
    username = username
      .replace(/[^a-z0-9.]/g, '') // Remove invalid characters
      .replace(/\.+/g, '.') // Remove multiple dots
      .replace(/^\.|\.$/g, ''); // Remove dots at start/end
    
    return username;
  };

  const fetchAvailableUsers = async () => {
    try {
      const response = await adminApi.getAvailableUsers();
      
      if (response.data && response.data.success) {
        setAvailableUsers(response.data.users || []);
      } else {
        setAvailableUsers([]);
      }
    } catch (err) {
      console.error("Error fetching available users:", err);
      setAvailableUsers([]);
    }
  };

  const handleUsernameOptionChange = (option) => {
    setUsernameOption(option);
    if (option === "auto") {
      // Set auto-generated username
      setFormData(prev => ({
        ...prev,
        username: usernameAutoGenerated
      }));
    } else {
      // Clear username for custom input
      setFormData(prev => ({
        ...prev,
        username: ""
      }));
    }
  };

  const handleInputChange = (e) => {
    const { name, value } = e.target;
    setFormData(prev => ({
      ...prev,
      [name]: value
    }));
  };

  // ADD THIS MISSING FUNCTION
  const handleCreateAccount = async () => {
    // Reset messages
    setError("");
    setSuccess("");
    
    // Validation
    if (!formData.username.trim()) {
      setError("Username is required");
      return;
    }
    
    // Username validation
    const usernameRegex = /^[a-zA-Z0-9._-]+$/;
    if (!usernameRegex.test(formData.username)) {
      setError("Username can only contain letters, numbers, dots, hyphens and underscores");
      return;
    }
    
    if (formData.username.length < 3) {
      setError("Username must be at least 3 characters long");
      return;
    }
    
    if (formData.username.length > 30) {
      setError("Username cannot exceed 30 characters");
      return;
    }
    
    if (!formData.password) {
      setError("Password is required");
      return;
    }
    if (formData.password.length < 8) {
      setError("Password must be at least 8 characters");
      return;
    }
    if (formData.password !== formData.confirm_password) {
      setError("Passwords do not match");
      return;
    }

    setLoading(true);
    
    try {
      // Method 1: Direct user creation
      const userData = {
        username: formData.username,
        email: staff.Email,
        password: formData.password,
        confirm_password: formData.confirm_password,
        role: staff.Role
      };
      
      const response = await adminApi.createUser(userData);
      
      if (response.data && response.data.success) {
        const userId = response.data.user.id;
        
        // Link the created user to staff
        const linkResponse = await adminApi.linkStaffToUser(staff.STAFF_ID, userId);
        
        if (linkResponse.data && linkResponse.data.success) {
          setSuccess(`Account created successfully for ${staff.Name}!`);
          
          // Auto close after success
          setTimeout(() => {
            if (onSuccess) onSuccess();
            onClose();
          }, 1500);
        } else {
          throw new Error(linkResponse.data?.error || "Failed to link account");
        }
      } else {
        throw new Error(response.data?.error || "Failed to create user");
      }
      
    } catch (err) {
      console.error("Error creating account:", err);
      
      // Try alternative method
      try {
        // Method 2: Create via staff endpoint
        const accountData = {
          username: formData.username,
          password: formData.password,
        };
        
        const response = await adminApi.createStaffUserAccount(staff.STAFF_ID, accountData);
        
        if (response.data && response.data.success) {
          setSuccess(`Account created successfully for ${staff.Name}!`);
          
          setTimeout(() => {
            if (onSuccess) onSuccess();
            onClose();
          }, 1500);
        } else {
          setError(response.data?.error || "Failed to create account");
        }
      } catch (secondErr) {
        console.error("Second attempt failed:", secondErr);
        setError(err.response?.data?.error || err.response?.data?.message || err.message || "Failed to create account. Please try again.");
      }
    } finally {
      setLoading(false);
    }
  };

  // ADD THIS MISSING FUNCTION
  const handleLinkAccount = async () => {
    if (!selectedUserId) {
      setError("Please select a user to link");
      return;
    }

    setLoading(true);
    setError("");
    
    try {
      const response = await adminApi.linkStaffToUser(staff.STAFF_ID, selectedUserId);
      
      if (response.data && response.data.success) {
        setSuccess(`Staff ${staff.Name} linked to user account successfully!`);
        setTimeout(() => {
          if (onSuccess) onSuccess();
          onClose();
        }, 1500);
      } else {
        setError(response.data?.error || "Failed to link account");
      }
      
    } catch (err) {
      console.error("Error linking account:", err);
      setError(err.response?.data?.error || err.response?.data?.message || "Failed to link account. Please try again.");
    } finally {
      setLoading(false);
    }
  };

  // ADD THIS MISSING FUNCTION
  const handleSubmit = async () => {
    if (mode === "create") {
      await handleCreateAccount();
    } else {
      await handleLinkAccount();
    }
  };

  if (!show || !staff) return null;

  return (
    <div className="modal fade show d-block" style={{ backgroundColor: 'rgba(0,0,0,0.5)' }}>
      <div className="modal-dialog modal-lg">
        <div className="modal-content">
          <div className="modal-header">
            <h5 className="modal-title">
              <i className="bi bi-person-gear me-2"></i>
              Add User Account for {staff.Name}
            </h5>
            <button type="button" className="btn-close" onClick={onClose}></button>
          </div>
          
          <div className="modal-body">
            {/* Staff Info */}
            <div className="alert alert-info mb-4">
              <div className="row">
                <div className="col-md-3">
                  <strong>Staff ID:</strong><br />
                  <span className="badge bg-secondary">#{staff.STAFF_ID}</span>
                </div>
                <div className="col-md-3">
                  <strong>Role:</strong><br />
                  <span className="badge bg-primary">{staff.Role}</span>
                </div>
                <div className="col-md-6">
                  <strong>Email:</strong><br />
                  {staff.Email}
                </div>
              </div>
            </div>

            {/* Mode Selector */}
            <div className="mb-4">
              <div className="btn-group w-100" role="group">
                <button
                  type="button"
                  className={`btn ${mode === 'create' ? 'btn-primary' : 'btn-outline-primary'}`}
                  onClick={() => setMode('create')}
                >
                  <i className="bi bi-person-plus me-2"></i>
                  Create New Account
                </button>
                <button
                  type="button"
                  className={`btn ${mode === 'link' ? 'btn-primary' : 'btn-outline-primary'}`}
                  onClick={() => setMode('link')}
                >
                  <i className="bi bi-link-45deg me-2"></i>
                  Link to Existing User
                </button>
              </div>
            </div>

            {/* Success/Error Messages */}
            {success && (
              <div className="alert alert-success alert-dismissible fade show">
                <i className="bi bi-check-circle me-2"></i>
                {success}
                <button type="button" className="btn-close" onClick={() => setSuccess("")}></button>
              </div>
            )}

            {error && (
              <div className="alert alert-danger alert-dismissible fade show">
                <i className="bi bi-exclamation-triangle me-2"></i>
                {error}
                <button type="button" className="btn-close" onClick={() => setError("")}></button>
              </div>
            )}

            {/* Create Account Form */}
            {mode === "create" && (
              <div className="row g-3">
                {/* Username Section */}
                <div className="col-md-12">
                  <label className="form-label">Username</label>
                  
                  <div className="mb-3">
                    <div className="form-check form-check-inline">
                      <input
                        className="form-check-input"
                        type="radio"
                        id="usernameAuto"
                        checked={usernameOption === "auto"}
                        onChange={() => handleUsernameOptionChange("auto")}
                      />
                      <label className="form-check-label" htmlFor="usernameAuto">
                        Auto-generate from staff name
                      </label>
                    </div>
                    <div className="form-check form-check-inline">
                      <input
                        className="form-check-input"
                        type="radio"
                        id="usernameCustom"
                        checked={usernameOption === "custom"}
                        onChange={() => handleUsernameOptionChange("custom")}
                      />
                      <label className="form-check-label" htmlFor="usernameCustom">
                        Enter custom username
                      </label>
                    </div>
                  </div>
                  
                  {usernameOption === "auto" ? (
                    <div className="alert alert-light border">
                      <div className="d-flex justify-content-between align-items-center">
                        <div>
                          <strong>Auto-generated Username:</strong><br />
                          <code className="fs-5">{usernameAutoGenerated}</code>
                        </div>
                        <button 
                          type="button" 
                          className="btn btn-sm btn-outline-secondary"
                          onClick={() => {
                            // Regenerate username
                            const newUsername = generateAutoUsername(staff);
                            setUsernameAutoGenerated(newUsername);
                            setFormData(prev => ({ ...prev, username: newUsername }));
                          }}
                        >
                          <i className="bi bi-arrow-clockwise"></i> Regenerate
                        </button>
                      </div>
                      <input
                        type="hidden"
                        name="username"
                        value={usernameAutoGenerated}
                      />
                    </div>
                  ) : (
                    <div>
                      <input
                        type="text"
                        className="form-control"
                        name="username"
                        value={formData.username}
                        onChange={handleInputChange}
                        placeholder="Enter custom username"
                        required
                        minLength="3"
                        maxLength="30"
                      />
                      <div className="form-text">
                        Use letters, numbers, dots, hyphens or underscores. 3-30 characters.
                      </div>
                    </div>
                  )}
                </div>
                
                {/* Password Fields */}
                <div className="col-md-6">
                  <label className="form-label">Password *</label>
                  <input
                    type="password"
                    className="form-control"
                    name="password"
                    value={formData.password}
                    onChange={handleInputChange}
                    placeholder="Enter password"
                    required
                    minLength="8"
                  />
                  <div className="form-text">Minimum 8 characters</div>
                </div>
                <div className="col-md-6">
                  <label className="form-label">Confirm Password *</label>
                  <input
                    type="password"
                    className="form-control"
                    name="confirm_password"
                    value={formData.confirm_password}
                    onChange={handleInputChange}
                    placeholder="Confirm password"
                    required
                  />
                </div>
                
                {/* Account Info */}
                <div className="col-12">
                  <div className="alert alert-light border">
                    <small>
                      <strong>Account will be created with role:</strong> <span className="badge bg-primary">{staff.Role}</span><br />
                      <strong>Email:</strong> {staff.Email}<br />
                      {usernameOption === "auto" && (
                        <>
                          <strong>Username format:</strong> firstname.lastname.staffid<br />
                          <strong>Generated username:</strong> <code>{usernameAutoGenerated}</code>
                        </>
                      )}
                    </small>
                  </div>
                </div>
              </div>
            )}

            {/* Link Account Form */}
            {mode === "link" && (
              <div>
                <label className="form-label">Select User to Link *</label>
                {availableUsers.length === 0 ? (
                  <div className="alert alert-warning">
                    <i className="bi bi-info-circle me-2"></i>
                    No available users found. Please create a new user account first.
                  </div>
                ) : (
                  <select
                    className="form-select"
                    value={selectedUserId}
                    onChange={(e) => setSelectedUserId(e.target.value)}
                    required
                  >
                    <option value="">Select a user...</option>
                    {availableUsers.map(user => (
                      <option key={user.id} value={user.id}>
                        {user.username} ({user.email}) - {user.role || 'No role'}
                      </option>
                    ))}
                  </select>
                )}
                
                {selectedUserId && (
                  <div className="mt-3 alert alert-info">
                    <strong>Selected User:</strong><br />
                    {availableUsers.find(u => u.id === parseInt(selectedUserId))?.username}
                  </div>
                )}
              </div>
            )}
          </div>
          
          <div className="modal-footer">
            <button type="button" className="btn btn-secondary" onClick={onClose} disabled={loading}>
              Cancel
            </button>
            <button
              type="button"
              className="btn btn-primary"
              onClick={handleSubmit}
              disabled={loading || (mode === 'link' && availableUsers.length === 0)}
            >
              {loading ? (
                <>
                  <span className="spinner-border spinner-border-sm me-2"></span>
                  Processing...
                </>
              ) : mode === 'create' ? (
                <>
                  <i className="bi bi-person-plus me-2"></i>
                  Create Account
                </>
              ) : (
                <>
                  <i className="bi bi-link-45deg me-2"></i>
                  Link Account
                </>
              )}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};

export default AddAccountModal;