# Generated by Django 5.2.8 on 2025-12-04 12:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctorapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineDetail',
            fields=[
                ('MED_ID', models.AutoField(primary_key=True, serialize=False, verbose_name='Medicine ID')),
                ('Medicine_Name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Medicine name can only contain letters, numbers, spaces, hyphens and parentheses', regex='^[A-Za-z0-9\\s\\-\\(\\)]+$')], verbose_name='Medicine Name')),
                ('Dosage', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Dosage should be in format like "500 mg" or "10 ml"', regex='^[\\d\\.]+\\s*[a-zA-Z]*$')], verbose_name='Dosage')),
                ('Price_per_Unit', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01, message='Price must be at least 0.01'), django.core.validators.MaxValueValidator(10000, message='Price cannot exceed 10000')], verbose_name='Price per Unit')),
            ],
            options={
                'verbose_name': 'Medicine Detail',
                'verbose_name_plural': 'Medicine Details',
                'db_table': 'MEDICINE_DETAILS',
            },
        ),
        migrations.CreateModel(
            name='SupplierDetail',
            fields=[
                ('SUPPLIER_ID', models.AutoField(primary_key=True, serialize=False, verbose_name='Supplier ID')),
                ('Supplier_Name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Supplier name can only contain letters, spaces, dots, hyphens and ampersand', regex='^[A-Za-z\\s\\.\\-&]+$')], verbose_name='Supplier Name')),
                ('Phone_Number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits (no symbols or spaces)', regex='^\\d{10}$')], verbose_name='Phone Number')),
            ],
            options={
                'verbose_name': 'Supplier Detail',
                'verbose_name_plural': 'Supplier Details',
                'db_table': 'SUPPLIER_DETAILS',
            },
        ),
        migrations.CreateModel(
            name='MedicineBatch',
            fields=[
                ('BATCH_ID', models.AutoField(primary_key=True, serialize=False, verbose_name='Batch ID')),
                ('Batch_Number', models.CharField(max_length=100, unique=True, verbose_name='Batch Number')),
                ('Expiry_Date', models.DateField(verbose_name='Expiry Date')),
                ('Quantity_Received', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantity Received')),
                ('Quantity_Available', models.IntegerField(help_text='Available quantity in this batch', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantity Available')),
                ('Purchase_Date', models.DateField(auto_now_add=True, verbose_name='Purchase Date')),
                ('Unit_Cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Unit Cost')),
                ('Is_Active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('MED_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacistapp.medicinedetail', verbose_name='Medicine')),
                ('SUPPLIER_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacistapp.supplierdetail', verbose_name='Supplier')),
            ],
            options={
                'verbose_name': 'Medicine Batch',
                'verbose_name_plural': 'Medicine Batches',
                'db_table': 'MEDICINE_BATCHES',
                'ordering': ['Expiry_Date'],
            },
        ),
        migrations.CreateModel(
            name='DispensingMedicine',
            fields=[
                ('DISPENSE_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Qty', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Quantity must be at least 1'), django.core.validators.MaxValueValidator(1000, message='Quantity cannot exceed 1000 units per dispense')])),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01, message='Price must be at least 0.01'), django.core.validators.MaxValueValidator(10000, message='Price cannot exceed 10,000')])),
                ('Dispense_Date', models.DateTimeField(auto_now_add=True)),
                ('CONSULT_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctorapp.consultationdetail')),
                ('Batch_Used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacistapp.medicinebatch')),
                ('MED_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacistapp.medicinedetail')),
            ],
            options={
                'db_table': 'DISPENSING_MEDICINES',
            },
        ),
        migrations.CreateModel(
            name='StockAlert',
            fields=[
                ('ALERT_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Alert_Type', models.CharField(choices=[('low_stock', 'Low Stock'), ('near_expiry', 'Near Expiry'), ('out_of_stock', 'Out of Stock'), ('expired', 'Expired Medicine')], max_length=20)),
                ('Message', models.TextField()),
                ('Is_Active', models.BooleanField(default=True)),
                ('Created_Date', models.DateTimeField(auto_now_add=True)),
                ('Resolved_Date', models.DateTimeField(blank=True, null=True)),
                ('MED_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacistapp.medicinedetail')),
            ],
            options={
                'db_table': 'STOCK_ALERTS',
                'ordering': ['-Created_Date'],
            },
        ),
        migrations.CreateModel(
            name='StockDetails',
            fields=[
                ('STOCK_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Earliest_Expiry', models.DateField(blank=True, help_text='Earliest expiry among active batches', null=True)),
                ('Total_Stock_Availability', models.IntegerField(default=0, help_text='Total available stock across all batches', validators=[django.core.validators.MinValueValidator(0)])),
                ('Minimum_Stock_Level', models.IntegerField(default=10, help_text='Alert when total stock goes below this level', validators=[django.core.validators.MinValueValidator(0)])),
                ('MED_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacistapp.medicinedetail')),
            ],
            options={
                'verbose_name_plural': 'Stock Summaries',
                'db_table': 'STOCK_DETAILS',
            },
        ),
        migrations.CreateModel(
            name='StockOrderingDetail',
            fields=[
                ('SUPPLY_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Qty_Supplied', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Quantity must be at least 1'), django.core.validators.MaxValueValidator(10000, message='Quantity cannot exceed 10,000 units')])),
                ('Date_of_Supply', models.DateField()),
                ('Supply_Cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01, message='Cost must be at least 0.01'), django.core.validators.MaxValueValidator(1000000, message='Cost cannot exceed 1,000,000')])),
                ('Batch_Number', models.CharField(blank=True, help_text='Auto-generated if empty', max_length=100)),
                ('Expiry_Date', models.DateField(help_text='Expiry date for this supply batch')),
                ('MED_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacistapp.medicinedetail')),
                ('SUPPLIER_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacistapp.supplierdetail')),
            ],
            options={
                'db_table': 'STOCK_ORDERING_DETAILS',
            },
        ),
    ]
