# Generated by Django 5.2.8 on 2025-11-19 11:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctorapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineDetails',
            fields=[
                ('MED_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Medicine_Name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Medicine name can only contain letters, numbers, spaces, hyphens and parentheses', regex='^[A-Za-z0-9\\s\\-\\(\\)]+$')])),
                ('Dosage', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Dosage should be in format like "500 mg" or "10 ml"', regex='^[\\d\\.]+\\s*[a-zA-Z]*$')])),
                ('Price_per_Unit', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01, message='Price must be at least 0.01'), django.core.validators.MaxValueValidator(10000, message='Price cannot exceed 10000')])),
            ],
            options={
                'db_table': 'MEDICINE_DETAILS',
            },
        ),
        migrations.CreateModel(
            name='SupplierDetails',
            fields=[
                ('SUPPLIER_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Supplier_Name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Supplier name can only contain letters, spaces, dots, hyphens and ampersand', regex='^[A-Za-z\\s\\.\\-&]+$')])),
                ('Phone_Number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits (no symbols or spaces)', regex='^\\d{10}$')])),
            ],
            options={
                'db_table': 'SUPPLIER_DETAILS',
            },
        ),
        migrations.CreateModel(
            name='DispensingMedicines',
            fields=[
                ('DISPENSE_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Qty', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Quantity must be at least 1'), django.core.validators.MaxValueValidator(1000, message='Quantity cannot exceed 1000 units per dispense')])),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01, message='Price must be at least 0.01'), django.core.validators.MaxValueValidator(10000, message='Price cannot exceed 10,000')])),
                ('Dispense_Date', models.DateTimeField(auto_now_add=True)),
                ('CONSULT_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctorapp.consultationdetails')),
                ('MED_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacistapp.medicinedetails')),
            ],
            options={
                'db_table': 'DISPENSING_MEDICINES',
            },
        ),
        migrations.CreateModel(
            name='StockOrderingDetails',
            fields=[
                ('SUPPLY_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Qty_Supplied', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Quantity must be at least 1'), django.core.validators.MaxValueValidator(10000, message='Quantity cannot exceed 10,000 units')])),
                ('Date_of_Supply', models.DateField()),
                ('Supply_Cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01, message='Cost must be at least 0.01'), django.core.validators.MaxValueValidator(1000000, message='Cost cannot exceed 1,000,000')])),
                ('MED_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacistapp.medicinedetails')),
                ('SUPPLIER_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacistapp.supplierdetails')),
            ],
            options={
                'db_table': 'STOCK_ORDERING_DETAILS',
            },
        ),
        migrations.CreateModel(
            name='StockDetails',
            fields=[
                ('STOCK_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Expiry_Date', models.DateField()),
                ('Stock_Availability', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='Stock cannot be negative'), django.core.validators.MaxValueValidator(100000, message='Stock cannot exceed 100,000 units')])),
                ('MED_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacistapp.medicinedetails')),
                ('SUPPLIER_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacistapp.supplierdetails')),
            ],
            options={
                'db_table': 'STOCK_DETAILS',
            },
        ),
    ]
