# Generated by Django 5.2.8 on 2025-12-09 13:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('DEPT_ID', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='Department ID')),
                ('Department_Name', models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='Department name can only contain letters, spaces and ampersand', regex='^[A-Za-z\\s&]+$')], verbose_name='Department Name')),
                ('Description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'db_table': 'DEPARTMENTS',
                'ordering': ['DEPT_ID'],
            },
        ),
        migrations.CreateModel(
            name='StaffDetail',
            fields=[
                ('STAFF_ID', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='Staff ID')),
                ('Name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Name can only contain letters, spaces, dots and hyphens', regex='^[A-Za-z\\s\\.\\-]+$')], verbose_name='Full Name')),
                ('Gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True, verbose_name='Gender')),
                ('Date_of_Birth', models.DateField(verbose_name='Date of Birth')),
                ('Age', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(18, message='Staff must be at least 18 years old'), django.core.validators.MaxValueValidator(70, message='Staff age cannot exceed 70 years')], verbose_name='Age')),
                ('Blood_Group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3, null=True, verbose_name='Blood Group')),
                ('Address', models.TextField(verbose_name='Address')),
                ('City', models.CharField(blank=True, max_length=50, null=True, verbose_name='City')),
                ('State', models.CharField(blank=True, max_length=50, null=True, verbose_name='State')),
                ('Pincode', models.CharField(blank=True, max_length=6, null=True, verbose_name='Pincode')),
                ('Phone_Number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must start with 6-9 and be exactly 10 digits (Indian standard)', regex='^[6-9]\\d{9}$')], verbose_name='Phone Number')),
                ('Alternate_Phone', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Alternate phone must start with 6-9 and be exactly 10 digits (Indian standard)', regex='^[6-9]\\d{9}$')], verbose_name='Alternate Phone')),
                ('Emergency_Contact', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Emergency contact must start with 6-9 and be exactly 10 digits (Indian standard)', regex='^[6-9]\\d{9}$')], verbose_name='Emergency Contact')),
                ('Email', models.EmailField(max_length=100, validators=[django.core.validators.RegexValidator(message='Enter a valid email address with proper domain', regex='^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$')], verbose_name='Email Address')),
                ('Role', models.CharField(choices=[('Admin', 'Admin'), ('Doctor', 'Doctor'), ('Receptionist', 'Receptionist'), ('Lab Technician', 'Lab Technician'), ('Pharmacist', 'Pharmacist'), ('Nurse', 'Nurse'), ('Physiotherapist', 'Physiotherapist'), ('Radiologist', 'Radiologist'), ('Accountant', 'Accountant'), ('Ward Boy', 'Ward Boy'), ('Cleaner', 'Cleaner'), ('Security Guard', 'Security Guard')], max_length=20, verbose_name='Role')),
                ('Qualification', models.CharField(blank=True, max_length=200, null=True, verbose_name='Primary Qualification')),
                ('Specialization', models.CharField(blank=True, max_length=100, null=True, verbose_name='Specialization')),
                ('Experience', models.IntegerField(blank=True, null=True, verbose_name='Experience (Years)')),
                ('License_Number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Primary License Number')),
                ('Consultation_fees', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='Consultation fees cannot be negative'), django.core.validators.MaxValueValidator(50000, message='Consultation fees cannot exceed ₹50,000')], verbose_name='Consultation Fees')),
                ('Status', models.CharField(choices=[('Available', 'Available'), ('Busy', 'Busy'), ('UnAvailable', 'UnAvailable')], default='Available', max_length=20, verbose_name='Status')),
                ('Joining_Date', models.DateField(blank=True, null=True, verbose_name='Joining Date')),
                ('Shift_Timing', models.CharField(blank=True, max_length=50, null=True, verbose_name='Shift Timing')),
                ('Salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salary')),
                ('Bank_Name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bank Name')),
                ('Account_Number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Account Number')),
                ('IFSC_Code', models.CharField(blank=True, max_length=11, null=True, verbose_name='IFSC Code')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('account_active', models.BooleanField(default=True, verbose_name='Account Active')),
                ('account_created_at', models.DateTimeField(blank=True, null=True, verbose_name='Account Created')),
                ('account_deactivated_at', models.DateTimeField(blank=True, null=True, verbose_name='Account Deactivated')),
                ('last_password_reset', models.DateTimeField(blank=True, null=True, verbose_name='Last Password Reset')),
                ('Department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_details', to='adminapp.department', verbose_name='Department')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_detail', to=settings.AUTH_USER_MODEL, verbose_name='User Account')),
            ],
            options={
                'verbose_name': 'Staff Detail',
                'verbose_name_plural': 'Staff Details',
                'db_table': 'STAFF_DETAILS',
                'ordering': ['STAFF_ID'],
            },
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification_name', models.CharField(help_text='e.g., MBBS, MD, B.Pharm, DMLT, etc.', max_length=200, verbose_name='Qualification Name')),
                ('institution', models.CharField(blank=True, max_length=300, null=True, verbose_name='Institution/University')),
                ('year_completed', models.IntegerField(validators=[django.core.validators.MinValueValidator(1950, message='Year must be after 1950'), django.core.validators.MaxValueValidator(2030, message='Year cannot be in the distant future')], verbose_name='Year Completed')),
                ('specialization', models.CharField(blank=True, max_length=200, null=True, verbose_name='Specialization')),
                ('registration_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Registration/License Number')),
                ('is_primary', models.BooleanField(default=False, help_text='Mark as primary qualification for this role', verbose_name='Primary Qualification')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='adminapp.staffdetail', verbose_name='Staff Member')),
            ],
            options={
                'verbose_name': 'Qualification',
                'verbose_name_plural': 'Qualifications',
                'db_table': 'STAFF_QUALIFICATIONS',
                'ordering': ['-is_primary', '-year_completed'],
            },
        ),
    ]
