# Generated by Django 5.2.8 on 2025-12-03 08:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('DEPT_ID', models.AutoField(primary_key=True, serialize=False, verbose_name='Department ID')),
                ('Department_Name', models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='Department name can only contain letters, spaces and ampersand', regex='^[A-Za-z\\s&]+$')], verbose_name='Department Name')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'db_table': 'DEPARTMENTS',
            },
        ),
        migrations.CreateModel(
            name='StaffDetail',
            fields=[
                ('STAFF_ID', models.AutoField(primary_key=True, serialize=False, verbose_name='Staff ID')),
                ('Name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Name can only contain letters, spaces, dots and hyphens', regex='^[A-Za-z\\s\\.\\-]+$')], verbose_name='Full Name')),
                ('Age', models.IntegerField(validators=[django.core.validators.MinValueValidator(18, message='Staff must be at least 18 years old'), django.core.validators.MaxValueValidator(70, message='Staff age cannot exceed 70 years')], verbose_name='Age')),
                ('Address', models.CharField(max_length=255, verbose_name='Address')),
                ('Phone_Number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits (no symbols or spaces)', regex='^\\d{10}$')], verbose_name='Phone Number')),
                ('Email', models.EmailField(max_length=100, validators=[django.core.validators.RegexValidator(message='Enter a valid email address with proper domain', regex='^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$')], verbose_name='Email Address')),
                ('Role', models.CharField(choices=[('Admin', 'Admin'), ('Doctor', 'Doctor'), ('Receptionist', 'Receptionist'), ('Lab Technician', 'Lab Technician'), ('Pharmacist', 'Pharmacist')], max_length=20, verbose_name='Role')),
                ('Consultation_fees', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='Consultation fees cannot be negative'), django.core.validators.MaxValueValidator(10000, message='Consultation fees cannot exceed 10000')], verbose_name='Consultation Fees')),
                ('Status', models.CharField(choices=[('Available', 'Available'), ('Busy', 'Busy'), ('On Leave', 'On Leave')], default='Available', max_length=20, verbose_name='Status')),
                ('Department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapp.department', verbose_name='Department')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_detail', to=settings.AUTH_USER_MODEL, verbose_name='User Account')),
            ],
            options={
                'verbose_name': 'Staff Detail',
                'verbose_name_plural': 'Staff Details',
                'db_table': 'STAFF_DETAILS',
            },
        ),
    ]
